export const iata: Record<string, string> = {
  AMS: 'Amsterdam, Netherlands',
  AMM: 'Amman, Jordan',
  ADL: 'Adelaide, SA, Australia',
  QWJ: 'Americana, Brazil',
  ACC: 'Accra, Ghana',
  AMD: 'Ahmedabad, India',
  IAD: 'Ashburn, VA, United States',
  AKL: 'Auckland, New Zealand',
  ATH: 'Athens, Greece',
  ARI: 'Arica, Chile',
  ALG: 'Algiers, Algeria',
  ALA: 'Almaty, Kazakhstan',
  LLK: 'Astara, Azerbaijan',
  ATL: 'Atlanta, GA, United States',
  QLD: 'Brisbane, QLD, Australia',
  BCN: 'Barcelona, Spain',
  BGW: 'Baghdad, Iraq',
  ASU: 'Asunción, Paraguay',
  AAE: 'Annaba, Algeria',
  BEG: 'Belgrade, Serbia',
  GYD: 'Baku, Azerbaijan',
  BLR: 'Bangalore, India',
  TNR: 'Antananarivo, Madagascar',
  ACT: 'Canberra, ACT, Australia',
  BEL: 'Belém, Brazil',
  TXL: 'Berlin, Germany',
  BKK: 'Bangkok, Thailand',
  BOS: 'Boston, MA, United States',
  CPT: 'Cape Town, South Africa',
  CNF: 'Belo Horizonte, Brazil',
  BSR: 'Basra, Iraq',
  CHC: 'Christchurch, New Zealand',
  API: 'Area 1 - API',
  BEY: 'Beirut, Lebanon',
  BUF: 'Buffalo, NY, United States',
  BWN: 'Bandar Seri Begawan, Brunei',
  BNU: 'Blumenau, Brazil',
  GUM: 'Hagatna, Guam',
  BTS: 'Bratislava, Slovakia',
  BRU: 'Brussels, Belgium',
  YYC: 'Calgary, AB, Canada',
  BOG: 'Bogota, Colombia',
  DKR: 'Dakar, Senegal',
  DMM: 'Dammam, Saudi Arabia',
  VIC: 'Melbourne, VIC, Australia',
  DOH: 'Doha, Qatar',
  OTP: 'Bucharest, Romania',
  CLT: 'Charlotte, NC, United States',
  DAR: 'Dar es Salaam, Tanzania',
  BSB: 'Brasilia, Brazil',
  BBI: 'Bhubaneswar, India',
  ORD: 'Chicago, IL, United States',
  EZE: 'Buenos Aires, Argentina',
  DXB: 'Dubai, United Arab Emirates',
  JIB: 'Djibouti, Djibouti',
  BUD: 'Budapest, Hungary',
  CEB: 'Cebu, Philippines',
  NOU: 'Noumea, New Caledonia',
  PER: 'Perth, WA, Australia',
  DUR: 'Durban, South Africa',
  KIV: 'Chișinău, Moldova',
  CMH: 'Columbus, OH, United States',
  CFC: 'Cacador, Brazil',
  EBL: 'Erbil, Iraq',
  IXC: 'Chandigarh, India',
  DFW: 'Dallas, TX, United States',
  NSW: 'Sydney, NSW, Australia',
  CPH: 'Copenhagen, Denmark',
  VCP: 'Campinas, Brazil',
  CGD: 'Changde, China',
  HFA: 'Haifa, Israel',
  GBE: 'Gaborone, Botswana',
  MAA: 'Chennai, India',
  DEN: 'Denver, CO, United States',
  ORK: 'Cork, Ireland -  (ORK)',
  HRE: 'Harare, Zimbabwe',
  JED: 'Jeddah, Saudi Arabia',
  PPT: 'Tahiti, French Polynesia',
  JNB: 'Johannesburg, South Africa',
  KWI: 'Kuwait City, Kuwait',
  DUB: 'Dublin, Ireland',
  DTW: 'Detroit, MI, United States',
  DNS: 'Secondary DNS',
  COR: 'Córdoba, Argentina',
  SUV: 'Suva, Fiji',
  DUS: 'Düsseldorf, Germany',
  BAH: 'Manama, Bahrain',
  KGL: 'Kigali, Rwanda',
  CGP: 'Chittagong, Bangladesh',
  HNL: 'Honolulu, HI, United States',
  CGB: 'Cuiaba, Brazil',
  HBA: 'Hobart, Australia',
  MCT: 'Muscat, Oman',
  CMB: 'Colombo, Sri Lanka',
  IAH: 'Houston, TX, United States',
  EDI: 'Edinburgh, United Kingdom',
  LOS: 'Lagos, Nigeria',
  CWB: 'Curitiba, Brazil',
  FRA: 'Frankfurt, Germany',
  LAD: 'Luanda, Angola',
  IND: 'Indianapolis, IN, United States',
  DAC: 'Dhaka, Bangladesh',
  BYO: 'Bring Your Own IP (BYOIP)',
  FLN: 'Florianopolis, Brazil',
  NJF: 'Najaf, Iraq',
  JAX: 'Jacksonville, FL, United States',
  GVA: 'Geneva, Switzerland',
  FOR: 'Fortaleza, Brazil',
  MPM: 'Maputo, Mozambique',
  FUO: 'Foshan, China',
  XNH: 'Nasiriyah, Iraq',
  MBA: 'Mombasa, Kenya',
  MCI: 'Kansas City, MO, United States',
  ZDM: 'Ramallah',
  GOT: 'Gothenburg, Sweden',
  GEO: 'Georgetown, Guyana',
  FUK: 'Fukuoka, Japan',
  HAM: 'Hamburg, Germany',
  LAS: 'Las Vegas, NV, United States',
  RUH: 'Riyadh, Saudi Arabia',
  NBO: 'Nairobi, Kenya',
  GYN: 'Goiania, Brazil',
  FOC: 'Fuzhou, China',
  LAX: 'Los Angeles, CA, United States',
  CAN: 'Guangzhou, China',
  HEL: 'Helsinki, Finland',
  GUA: 'Guatemala City, Guatemala',
  CDN: 'CDN Cache Purge',
  ISU: 'Sulaymaniyah, Iraq',
  ORN: 'Oran, Algeria',
  MFE: 'McAllen, TX, United States',
  IST: 'Istanbul, Turkey',
  TLV: 'Tel Aviv, Israel',
  GYE: 'Guayaquil, Ecuador',
  HAK: 'Chengmai, China',
  OUA: 'Ouagadougou, Burkina Faso',
  MRU: 'Port Louis, Mauritius',
  MEM: 'Memphis, TN, United States',
  HAN: 'Hanoi, Vietnam',
  ITJ: 'Itajai, Brazil',
  ADB: 'Izmir, Turkey',
  KBP: 'Kyiv, Ukraine',
  MEX: 'Mexico City, Mexico',
  RUN: 'Saint-Denis, Réunion',
  SJW: 'Shijiazhuang, China',
  JOI: 'Joinville, Brazil',
  CAS: 'Cloud Access Security Broker (CASB)',
  MIA: 'Miami, FL, United States',
  LIS: 'Lisbon, Portugal',
  SGN: 'Ho Chi Minh City, Vietnam',
  TUN: 'Tunis, Tunisia',
  JDO: 'Juazeiro do Norte, Brazil',
  LHR: 'London, United Kingdom',
  HKG: 'Hong Kong',
  LIM: 'Lima, Peru',
  MSP: 'Minneapolis, MN, United States',
  FIH: 'Kinshasa, DR Congo',
  LUX: 'Luxembourg City, Luxembourg',
  HYD: 'Hyderabad, India',
  MAO: 'Manaus, Brazil',
  CAI: 'Cairo, Egypt',
  CNI: 'Cloud Network Interconnect (CNI)',
  MAD: 'Madrid, Spain',
  MDE: 'Medellín, Colombia',
  YUL: 'Montréal, QC, Canada',
  ISB: 'Islamabad, Pakistan',
  WDH: 'Windhoek, Namibia',
  MAN: 'Manchester, United Kingdom',
  CGK: 'Jakarta, Indonesia',
  NQN: 'Neuquen, Argentina',
  BNA: 'Nashville, United States',
  ASK: 'Yamoussoukro, Ivory Coast',
  EWR: 'Newark, NJ, United States',
  MRS: 'Marseille, France',
  PTY: 'Panama City, Panama',
  ABJ: 'Abidjan, Ivory Coast',
  MXP: 'Milan, Italy',
  TNA: 'Zibo, China',
  ORF: 'Norfolk, VA, United States',
  PBM: 'Paramaribo, Suriname',
  EBB: 'Kampala, Uganda',
  OMA: 'Omaha, NE, United States',
  POA: 'Porto Alegre, Brazil',
  MSQ: 'Minsk, Belarus',
  DME: 'Moscow, Russia',
  JHB: 'Johor Bahru, Malaysia - (JHB)',
  YOW: 'Ottawa, Canada',
  DLP: 'Data Loss Prevention (DLP)',
  UIO: 'Quito, Ecuador',
  MUC: 'Munich, Germany',
  PHL: 'Philadelphia, United States',
  KNU: 'Kanpur, India',
  PHX: 'Phoenix, AZ, United States',
  LCA: 'Nicosia, Cyprus',
  KHH: 'Kaohsiung City, Taiwan',
  REC: 'Recife, Brazil',
  OSL: 'Oslo, Norway',
  PIT: 'Pittsburgh, PA, United States',
  KHI: 'Karachi, Pakistan',
  RAO: 'Ribeirao Preto, Brazil',
  DEX: 'Digital Experience Monitoring (DEX)',
  GIG: 'Rio de Janeiro, Brazil',
  PDX: 'Portland, OR, United States',
  KTM: 'Kathmandu, Nepal',
  PMO: 'Palermo, Italy',
  CDG: 'Paris, France',
  QRO: 'Queretaro, MX, Mexico',
  PRG: 'Prague, Czech Republic',
  RIC: 'Richmond, VA, United States',
  CCU: 'Kolkata, India',
  SJO: 'San José, Costa Rica',
  SCL: 'Santiago, Chile',
  KEF: 'Reykjavík, Iceland',
  SMF: 'Sacramento, CA, United States',
  KJA: 'Krasnoyarsk, Russia',
  LUN: 'Lusaka, Zambia',
  KUL: 'Kuala Lumpur, Malaysia',
  SLC: 'Salt Lake City, UT, United States',
  RIX: 'Riga, Latvia',
  SDQ: 'Santo Domingo, Dominican Republic',
  ADD: 'Addis Ababa, Ethiopia',
  FCO: 'Rome, Italy',
  SAN: 'San Diego, CA, United States',
  LHE: 'Lahore, Pakistan',
  SJP: 'São José do Rio Preto, Brazil',
  SJC: 'San Jose, CA, United States',
  LED: 'Saint Petersburg, Russia',
  PKX: 'Langfang, China',
  SJK: 'São José dos Campos, Brazil',
  GRU: 'São Paulo, Brazil',
  SOF: 'Sofia, Bulgaria',
  YXE: 'Saskatoon, SK, Canada',
  SEA: 'Seattle, WA, United States',
  ARN: 'Stockholm, Sweden',
  SOD: 'Sorocaba, Brazil',
  MFM: 'Macau',
  FSD: 'Sioux Falls, South Dakota',
  STR: 'Stuttgart, Germany',
  STL: 'St. Louis, MO, United States',
  TLL: 'Tallinn, Estonia',
  MLE: 'Male, Maldives',
  TGU: 'Tegucigalpa, Honduras',
  TLH: 'Tallahassee, FL, United States',
  TBS: 'Tbilisi, Georgia',
  NVT: 'Timbo, Brazil',
  MNL: 'Manila, Philippines',
  SKG: 'Thessaloniki, Greece',
  UDI: 'Uberlandia, Brazil',
  YYZ: 'Toronto, ON, Canada',
  BOM: 'Mumbai, India',
  TIA: 'Tirana, Albania',
  VIX: 'Vitoria, Brazil',
  YVR: 'Vancouver, BC, Canada',
  NAG: 'Nagpur, India',
  VIE: 'Vienna, Austria',
  YWG: 'Winnipeg, MB, Canada',
  OKA: 'Naha, Japan',
  CAW: 'Campos dos Goytacazes, Brazil',
  DEL: 'New Delhi, India',
  VNO: 'Vilnius, Lithuania',
  SFO: 'San Francisco, United States',
  XAP: 'Chapeco, Brazil',
  WAW: 'Warsaw, Poland',
  KIX: 'Osaka, Japan',
  KIN: 'Kingston, Jamaica',
  BGI: 'Bridgetown, Barbados',
  PAT: 'Patna, India',
  BGR: 'Bangor, United States',
  GND: "St. George's, Grenada",
  ZAG: 'Zagreb, Croatia',
  PNH: 'Phnom Penh, Cambodia',
  AUS: 'Austin, United States',
  STI: 'Santiago de los Caballeros, Dominican Republic',
  ZRH: 'Zurich, Switzerland',
  TAO: 'Qingdao, China',
  ABQ: 'Albuquerque, United States',
  LPB: 'La Paz, Bolivia',
  ICN: 'Seoul, South Korea',
  LYS: 'Lyon, France',
  GDL: 'Guadalajara, Mexico',
  SHA: 'Shanghai, China',
  WAN: 'Magic WAN Connector',
  BOD: 'Bordeaux, France',
  SAT: 'San Antonio, United States',
  SJU: 'San Juan, Puerto Rico',
  SIN: 'Singapore, Singapore',
  CLE: 'Cleveland, United States',
  BAQ: 'Barranquilla, Colombia',
  SKP: 'Skopje, North Macedonia',
  URT: 'Surat Thani, Thailand',
  RDU: 'Durham, United States',
  PMW: 'Palmas, Brazil',
  TPE: 'Taipei',
  OKC: 'Oklahoma City, United States',
  ARU: 'Aracatuba, Brazil',
  TPA: 'Tampa, United States',
  POS: 'Port of Spain, Trinidad and Tobago',
  ANC: 'Anchorage, United States',
  SSA: 'Salvador, Brazil',
  YHZ: 'Halifax, Canada',
  NRT: 'Tokyo, Japan',
  ULN: 'Ulaanbaatar, Mongolia',
  VTE: 'Vientiane, Laos',
  KHN: 'Nanchang, China',
  SFU: 'Realtime SFU',
  TUR: 'Realtime TURN Service',
  EVN: 'Yerevan, Armenia',
  JOG: 'Yogyakarta, Indonesia',
  RDA: 'Registration Data Access Protocol (RDAP)',
  ZGN: 'Zhongshan, China',
  CGY: 'Cagayan de Oro, Philippines',
  SSL: 'SSL for SaaS Provisioning',
  COK: 'Kochi, India',
  DPS: 'Denpasar, Indonesia',
  CNN: 'Kannur, India',
  WAR: 'WARP',
  CLO: 'Cali, Colombia',
  SAP: 'San Pedro Sula, Honduras',
  SZX: 'Shenzhen, China',
  KWE: 'Guiyang, China',
  HGH: 'Shaoxing, China',
  CZX: 'Changzhou, China',
  KMG: 'Kunming, China',
  CNX: 'Chiang Mai, Thailand',
  CGO: 'Zhengzhou, China',
  TYN: 'Yangquan, China',
  CSX: 'Changsha, China',
  DLC: 'Dalian, China',
  BHY: 'Beihai, China',
  CKG: 'Chongqing, China',
  XFN: 'Xiangyang, China',
  DAD: 'Da Nang, Vietnam',
  JXG: 'Jiaxing, China',
  CRK: 'Tarlac City, Philippines',
  PBH: 'Thimphu, Bhutan',
  XIY: 'Baoji, China',
  CTU: 'Chengdu, China',
  NQZ: 'Astana, Kazakhstan',
  NNG: 'Nanning, China',
  KCH: 'Kuching, Malaysia',
  AKX: 'Aktobe, Kazakhstan',
  TEN: 'Tongren, China',
  HYN: 'Taizhou, China'
}
